# Generated by Django 5.1.6 on 2025-03-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("viewflow", "0014_alter_process_parent_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelloWorldProcess",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("viewflow.process",),
        ),
    ]
